Repository HackerSir/Articles-of-association, pull requests merged in 2020-01, with the labels that each got.

#26 新增 社團器材管理辦法
  equipment.md
Labels: 提案連署完成, 等待表決

#27 更新 器材管理辦法
  equipment.md
Labels: 表決通過

#29 新增 修訂日期
  equipment.md
Labels: 不須提案表決

#30 更新 修訂歷史
  Readme.md
  rules.md
Labels: 不須提案表決
